name: MLForEveryone
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - pip=22.0.3
  - numpy=1.20.3
  - scipy=1.7.1
  - pandas=1.3.4
  - pip:
      - -r requirements.txt